
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f23/team02-f23-7pm-1
owner: ucsb-cs156-f23
repo_name: team02-f23-7pm-1
pull_requests: [{"author":{"id":"U_kgDOBdDdWA","is_bot":false,"login":"awesomebob35","name":"Joseph Yue"},"headRefName":"jy-Articles-typo","number":66,"title":"fixed a typo with articles","url":"https://github.com/ucsb-cs156-f23/team02-f23-7pm-1/pull/66"},{"author":{"id":"U_kgDOBXu0Pg","is_bot":false,"login":"madhav-ucsb","name":""},"headRefName":"mr-HelpRequests-delete","number":65,"title":"Added delete api endpoint for helprequests table","url":"https://github.com/ucsb-cs156-f23/team02-f23-7pm-1/pull/65"},{"author":{"id":"U_kgDOBXu0Pg","is_bot":false,"login":"madhav-ucsb","name":""},"headRefName":"mr-HelpRequests-put","number":64,"title":"Added put api endpoint for help requests","url":"https://github.com/ucsb-cs156-f23/team02-f23-7pm-1/pull/64"}]
