
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f23/team02-f23-7pm-1
owner: ucsb-cs156-f23
repo_name: team02-f23-7pm-1
pull_requests: [{"author":{"id":"MDQ6VXNlcjMzMjcwMjMy","is_bot":false,"login":"Irreflexive","name":"Carson"},"headRefName":"Carson-UCSBDiningCommonsMenuItem-getById","number":50,"title":"Implemented getById and tests for UCSBDiningCommonsMenuItem","url":"https://github.com/ucsb-cs156-f23/team02-f23-7pm-1/pull/50"},{"author":{"id":"MDQ6VXNlcjMzMjcwMjMy","is_bot":false,"login":"Irreflexive","name":"Carson"},"headRefName":"Carson-UCSBDiningCommonsMenuItem-create-controller","number":49,"title":"Create UCSBDiningCommonsMenuItem controller and tests","url":"https://github.com/ucsb-cs156-f23/team02-f23-7pm-1/pull/49"},{"author":{"id":"U_kgDOBdDdWA","is_bot":false,"login":"awesomebob35","name":"Joseph Yue"},"headRefName":"jy-Articles-delete","number":48,"title":"Implemented Delete for Articles","url":"https://github.com/ucsb-cs156-f23/team02-f23-7pm-1/pull/48"},{"author":{"id":"U_kgDOBdDdWA","is_bot":false,"login":"awesomebob35","name":"Joseph Yue"},"headRefName":"jy-Articles-put","number":47,"title":"Implemented Put for Articles","url":"https://github.com/ucsb-cs156-f23/team02-f23-7pm-1/pull/47"},{"author":{"id":"U_kgDOBdDdWA","is_bot":false,"login":"awesomebob35","name":"Joseph Yue"},"headRefName":"jy-Articles-get","number":46,"title":"Implemented Get ID for Articles","url":"https://github.com/ucsb-cs156-f23/team02-f23-7pm-1/pull/46"},{"author":{"id":"U_kgDOBdDdWA","is_bot":false,"login":"awesomebob35","name":"Joseph Yue"},"headRefName":"jy-Articles-controller","number":45,"title":"Created Controller for Articles and Tested Get All and Put","url":"https://github.com/ucsb-cs156-f23/team02-f23-7pm-1/pull/45"},{"author":{"id":"MDQ6VXNlcjMzMjcwMjMy","is_bot":false,"login":"Irreflexive","name":"Carson"},"headRefName":"Carson-UCSBDiningCommonsMenuItem-create-db","number":44,"title":"Created database table for UCSBDiningCommonsMenuItem","url":"https://github.com/ucsb-cs156-f23/team02-f23-7pm-1/pull/44"},{"author":{"id":"U_kgDOBdDdWA","is_bot":false,"login":"awesomebob35","name":"Joseph Yue"},"headRefName":"jy-Articles-create-db","number":43,"title":"Created Database Table for Articles","url":"https://github.com/ucsb-cs156-f23/team02-f23-7pm-1/pull/43"}]
