
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f23/team02-f23-7pm-1
owner: ucsb-cs156-f23
repo_name: team02-f23-7pm-1
pull_requests: [{"author":{"id":"MDQ6VXNlcjczNDExMjEw","is_bot":false,"login":"mageswarankk","name":"Karankumar Mageswaran"},"headRefName":"Karankumar-UCSBOrganization-PUT","number":73,"title":"Added PUT function to Controller and Tests for UCSBOrganization","url":"https://github.com/ucsb-cs156-f23/team02-f23-7pm-1/pull/73"},{"author":{"id":"MDQ6VXNlcjczNDExMjEw","is_bot":false,"login":"mageswarankk","name":"Karankumar Mageswaran"},"headRefName":"Karankumar-UCSBOrganization-controller","number":72,"title":"Added Controller and Tests for UCSBOrganization along with GET (all)","url":"https://github.com/ucsb-cs156-f23/team02-f23-7pm-1/pull/72"},{"author":{"id":"U_kgDOBX3XnA","is_bot":false,"login":"daniel-li2021","name":""},"headRefName":"dl-RecommendationRequest-create-db","number":71,"title":"Added Controller and Tests for RecommendationRequest along with GET (all) #21","url":"https://github.com/ucsb-cs156-f23/team02-f23-7pm-1/pull/71"}]
